#!/usr/bin/env python3
"""Single source of truth for Hazel (round 2). Emits the SVGs, Android vector drawables and PNG renders.

Run from the repo root:  python3 docs/design/icon_candidates/round2/gen_hazel.py
Needs ImageMagick (`magick`). Geometry lives in 108x108 adaptive-icon units; FIT scales it into the safe zone.
Colours: fur, shade, cream, ink + the purple tile = 5 flat colours, no gradients. Smallest stroke is 4.4 units
(> 4% of 108); the smile is a filled crescent, not a stroke.
"""
import math, os, subprocess, sys

FUR, SHADE, CREAM, INK, BG = "#F0A04B", "#D9822B", "#FFF1D6", "#2B1B12", "#6750A4"
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "../../../.."))
RES = os.path.join(ROOT, "app/src/main/res/drawable")

# Global fit into the 66 dp safe zone (scale about the canvas centre, then nudge).
FIT_S, FIT_DX, FIT_DY = 0.85, -4.5, -1.0
TAIL = "M56,80 C78,84 84,62 70,55 C60,50 62,37 71,34"
TAIL_PIVOT = (56, 78)


def ell(cx, cy, rx, ry):
    return f"M{cx-rx:g},{cy:g}a{rx:g},{ry:g} 0 1,0 {2*rx:g},0a{rx:g},{ry:g} 0 1,0 {-2*rx:g},0z"


def circ(cx, cy, r):
    return ell(cx, cy, r, r)


# element: (kind, d, fill-or-stroke colour, stroke width)
def fill(d, c): return ("fill", d, c, 0)
def stroke(d, c, w, join="round"): return ("stroke", d, c, w)


EAR_L = "M35,38 L34.5,27 L45,33 Z"
EAR_R = "M61,38 L61.5,27 L51,33 Z"
EAR_IN_L = "M37,35 L37,30.5 L41.5,33.2 Z"
EAR_IN_R = "M59,35 L59,30.5 L54.5,33.2 Z"
SMILE = "M44,49.6 Q48,53.6 52,49.6 Q48,51.4 44,49.6 Z"

tail = [stroke(TAIL, SHADE, 17), stroke(TAIL, FUR, 6)]
body = [
    fill(ell(50, 69, 15, 17), FUR),
    fill(ell(50, 72, 9, 12), CREAM),
    fill(EAR_L, FUR), stroke(EAR_L, FUR, 2.4), fill(EAR_R, FUR), stroke(EAR_R, FUR, 2.4),
    fill(EAR_IN_L, CREAM), fill(EAR_IN_R, CREAM),
    fill(ell(48, 42, 15, 12.5), FUR),
    fill(ell(48, 47.6, 7, 5), CREAM),
    fill(ell(48, 45.4, 2.3, 1.7), INK),
    fill(SMILE, INK),
    fill(circ(41, 41, 3.3), INK), fill(circ(55, 41, 3.3), INK),
    fill(circ(42.1, 39.9, 1.1), CREAM), fill(circ(56.1, 39.9, 1.1), CREAM),
]
paws_rest = [fill(ell(41, 73, 4.6, 6), SHADE), fill(ell(55, 73, 4.6, 6), SHADE)]
LENS = (44, 68, 9)
HANDLE = "M50.4,74.4 L60,84"
lens = [
    fill(circ(*LENS), CREAM),
    stroke(circ(*LENS), INK, 5),
    stroke(HANDLE, INK, 5.6),
    fill(ell(36.4, 70, 4.4, 5.6), SHADE),   # left paw on the ring
    fill(ell(55, 78.6, 4.8, 4.4), SHADE),    # right paw on the handle
]
ACORN = [
    fill("M41,71 C41,80 44,83.5 48,83.5 C52,83.5 55,80 55,71 Z", SHADE),
    fill("M39.5,71 C39.5,63 43,61 48,61 C53,61 56.5,63 56.5,71 Z", INK),
    stroke("M48,61 L48,57.5", INK, 4.4),
    fill(ell(38.5, 74, 4.4, 5.6), SHADE), fill(ell(57.5, 74, 4.4, 5.6), SHADE),
]
LAYERS_A = [tail, body, lens]
LAYERS_B = [tail, body, ACORN]


# ---------------------------------------------------------------- emitters
def tf(): return f"translate({54+FIT_DX} {54+FIT_DY}) scale({FIT_S}) translate(-54 -54)"


def svg_el(e):
    k, d, c, w = e
    if k == "fill": return f'<path d="{d}" fill="{c}"/>'
    return f'<path d="{d}" fill="none" stroke="{c}" stroke-width="{w:g}" stroke-linecap="round" stroke-linejoin="round"/>'


def svg_group(layers):
    return "\n".join("    " + svg_el(e) for layer in layers for e in layer)


def svg_file(layers, bg=True, title=""):
    rect = f'  <rect width="108" height="108" fill="{BG}"/>\n' if bg else ""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108" width="432" height="432">\n'
            f'  <!-- {title} Generated by gen_hazel.py. Colours: {FUR} {SHADE} {CREAM} {INK} on {BG}. -->\n{rect}'
            f'  <g transform="{tf()}">\n{svg_group(layers)}\n  </g>\n</svg>\n')


def xml_el(e, mono=False):
    k, d, c, w = e
    col = "#000000" if mono else c
    if k == "fill":
        return f'    <path android:fillColor="{col}" android:pathData="{d}" />'
    return (f'    <path android:strokeColor="{col}" android:strokeWidth="{w:g}" android:strokeLineCap="round" '
            f'android:strokeLineJoin="round" android:pathData="{d}" />')


def vec(inner, w, h, vw, vh, comment):
    return (f'<?xml version="1.0" encoding="utf-8"?>\n<!-- {comment} -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n    android:width="{w}dp"\n'
            f'    android:height="{h}dp"\n    android:viewportWidth="{vw}"\n    android:viewportHeight="{vh}">\n{inner}\n</vector>\n')


def fit_group(body_xml):
    return (f'    <group android:translateX="{54+FIT_DX-54*FIT_S:g}" android:translateY="{54+FIT_DY-54*FIT_S:g}" '
            f'android:scaleX="{FIT_S}" android:scaleY="{FIT_S}">\n{body_xml}\n    </group>')


GEN = "Generated by docs/design/icon_candidates/round2/gen_hazel.py. Do not edit by hand."


def write(path, text):
    with open(path, "w") as f: f.write(text)


def xml_layers(layers): return "\n".join(xml_el(e) for layer in layers for e in layer)


# Monochrome: black silhouette; a clip with holes cuts the eyes and a gap round the lens so the lens reads.
def mono_xml():
    sil = [fill(ell(50, 69, 15, 17), "k"), fill(ell(48, 42, 15, 12.5), "k"), fill(EAR_L, "k"), stroke(EAR_L, "k", 2.4),
           fill(EAR_R, "k"), stroke(EAR_R, "k", 2.4), stroke(TAIL, "k", 17)]
    def rev(cx, cy, r):  # counter-clockwise circle = hole under the non-zero rule
        return f"M{cx-r:g},{cy:g}a{r:g},{r:g} 0 1,1 {2*r:g},0a{r:g},{r:g} 0 1,1 {-2*r:g},0z"
    holes = "M0,0H108V108H0Z" + rev(41, 41, 3.3) + rev(55, 41, 3.3) + rev(LENS[0], LENS[1], LENS[2] + 5.2)
    ring = [stroke(circ(*LENS), "k", 5), stroke(HANDLE, "k", 5.6), fill(ell(55, 78.6, 4.8, 4.4), "k")]
    inner = (f'        <group><clip-path android:pathData="{holes}" />\n'
             + "\n".join("    " + xml_el(e, True) for e in sil) + "\n        </group>\n"
             + "\n".join("    " + xml_el(e, True) for e in ring))
    return vec(fit_group(inner), 108, 108, 108, 108,
               "Themed-icon layer: one-colour Hazel silhouette (system recolours by alpha); eyes and a gap round the lens are cut out. " + GEN)


def tight(layer_xml, name):
    # In-app layers: 72x72 viewport cropped to the art (translate -18,-18), no purple tile, no safe-zone shrink.
    inner = f'    <group android:translateX="-18" android:translateY="-18">\n{layer_xml}\n    </group>'
    return vec(inner, 72, 72, 72, 72, f"In-app Hazel layer ({name}). Same geometry as the launcher icon. " + GEN)


def emit_android():
    write(f"{RES}/ic_launcher_foreground.xml",
          vec(fit_group(xml_layers(LAYERS_A)), 108, 108, 108, 108,
              "Launcher / splash foreground: Hazel holding a magnifier in both paws. " + GEN))
    write(f"{RES}/ic_launcher_monochrome.xml", mono_xml())
    write(f"{RES}/hazel_tail.xml", tight(xml_layers([tail]), "tail"))
    write(f"{RES}/hazel_body.xml", tight(xml_layers([body]), "body"))
    write(f"{RES}/hazel_paws_rest.xml", tight(xml_layers([paws_rest]), "resting paws"))
    write(f"{RES}/hazel_lens.xml", tight(xml_layers([lens]), "magnifier and paws"))


# ---------------------------------------------------------------- renders
def magick(*a):
    subprocess.run(["magick", *a], check=True)


def render(svg, png, px):
    magick("-background", "none", "-density", str(96 * px / 432 * 1.0 if False else 96), svg, "-resize", f"{px}x{px}", png)


def emit_previews():
    out = HERE
    for tag, layers in (("A_magnifier", LAYERS_A), ("B_acorn", LAYERS_B)):
        svg = os.path.join(out, f"hazel_{tag}.svg")
        write(svg, svg_file(layers, True, f"Variant {tag}."))
        fg = os.path.join(out, f"_fg_{tag}.svg")
        write(fg, svg_file(layers, False))
        for px in (48, 108, 432):
            base = os.path.join(out, f"hazel_{tag}_{px}.png")
            render(svg, base, px)
            for name, tile in (("dark", "#14121A"), ("light", "#F3EEF8")):
                m = px * 2
                # icon masked to a circle (66/108 safe-zone look) on a wallpaper tile
                magick("-size", f"{m}x{m}", f"xc:{tile}", "(", base, "-resize", f"{px}x{px}",
                       "(", "-size", f"{px}x{px}", "xc:black", "-fill", "white", "-draw",
                       f"circle {px/2},{px/2} {px/2},{px*0.04}", ")", "-alpha", "off", "-compose", "CopyOpacity", "-composite", ")",
                       "-gravity", "center", "-compose", "over", "-composite", os.path.join(out, f"hazel_{tag}_{px}_{name}.png"))
        os.remove(fg)


def radius_check():
    # max distance of any opaque pixel (foreground only, 432 px render) from the centre, in 108-unit space
    tmp = os.path.join(HERE, "_fgcheck.svg")
    write(tmp, svg_file(LAYERS_A, False))
    png = os.path.join(HERE, "_fgcheck.png")
    magick("-background", "none", "-density", "96", tmp, "-resize", "432x432", png)
    from PIL import Image
    im = Image.open(png).convert("RGBA"); a = im.split()[3]; w, h = im.size
    r = 0.0
    for y in range(h):
        for x in range(w):
            if a.getpixel((x, y)) > 40:
                r = max(r, math.hypot(x + .5 - w / 2, y + .5 - h / 2) * 108 / w)
    os.remove(tmp); os.remove(png)
    return r


if __name__ == "__main__":
    emit_android()
    if "--no-render" not in sys.argv:
        emit_previews()
    print("max radius of art (units, safe zone is 33):", round(radius_check(), 1))
